name: telegram_dart_webhook_server
description: Dart Telegram Webhook Server on Render
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http: ^0.13.6
